- hosts: pis
  roles:
    - ssh
    - ufw
    - name: python
      version: 3.7.9
      threads: 4
  tasks:
    - name: Install git.
      apt:
        name: git
        state: present
      become: yes

    - name: Install supervisor.
      apt:
        name: supervisor
        state: present
      become: yes

    # https://hackaday.com/2017/11/02/what-is-entropy-and-how-do-i-get-more-of-it/
    - name: Get the chip's hardware RNG contributing to system entropy.
      apt:
        name: rng-tools
        state: present
      become: yes
