- hosts: pis
  roles:
    - ssh
    - ufw
    - name: python
      version: 3.6.5
      threads: 4
    - pip
  tasks:
    - name: Install git.
      apt:
        name: git
        state: present
      become: yes

    - name: Install supervisor.
      apt:
        name: supervisor
        state: present
      become: yes

    # https://hackaday.com/2017/11/02/what-is-entropy-and-how-do-i-get-more-of-it/
    - name: Get the chip's hardware RNG contributing to system entropy.
      apt:
        name: rng-tools
        state: present
      become: yes

    - name: Copy requirements.txt to remote system.
      copy:
        src: requirements.txt
        dest: /tmp/requirements.txt

    - name: Create a venv with Python software requirements.
      pip:
        requirements: /tmp/requirements.txt
        virtualenv: /opt/caproto-venv
        extra_args: "--upgrade"
        virtualenv_command: /usr/local/bin/python3.6 -m venv
      become: true
